import { localize } from '@visionplanner/vp-ui-fiscal-library';

const { extend, translateWithPrefix } = localize();
export const createDossierTranslate = translateWithPrefix('dossier-monitor');
extend('nl', {
  'dossier-monitor': {
    'taxable-subjects': 'Belastingplichtigen',
    'tax-dossier-monitor': 'Aangiftemonitor',
    'full-name': 'Naam',
    'dossier-name': 'Dossiernaam',
    'dossier-type': 'Dossiertype',
    period: 'Tijdvak',
    year: 'Jaar',
    version: 'Versie',
    status: 'Status',
    'last-modified': 'Laatste wijziging',
    tasks: 'Taken',
    'search-tax-dossier-placeholder': 'Aangifte zoeken',
    forecast: 'Prognose',
    'provisional-declaration': 'Voorlopige aangifte',
    declaration: 'Aangifte',
    'in-progress': 'Opstellen',
    'in-review': 'Controleren',
    submitted: 'Ingediend',
    'in-approval': 'Accorderen',
    completed: 'Afgerond',
    'select-label': 'Selecteren',
    'select-all': 'Alles selecteren',
    'selected-label': 'Selected',
    'type-label': 'Type',
    'taxable-subject-label': 'Belastingplichtige',
    'create-button': 'Toevoegen',
    cancel: 'Annuleren',
    apply: 'Toepassen',
    'clear-all': 'Verwijderen',
    'tax-form': 'Biljetsoort',
    'p-form': 'P-biljet',
    'f-form': ' F-biljet',
    'c-form': 'C-biljet',
    'm-form': 'M-biljet',
    'date-of-death': 'Overlijdensdatum',
    'joint-declaration': 'Doet samen aangifte?',
    'fiscal-partner': 'Fiscaal partner',
    'create-dossier': 'Toevoegen inkomstenbelasting dossier',
    'required-field': 'Verplicht veld',
    'invalid-entry': 'Ongeldige invoer',
    date: 'Datum',
    'copy-dossier-form': 'Overnemen van',
  },
});
