import { localize } from '@visionplanner/vp-ui-fiscal-library';

const { extend, translateWithPrefix } = localize();

export const expenditureTranslate = translateWithPrefix('expenditure');

extend('nl', {
  expenditure: {
    'expenditure-heading': 'Uitgaven',
    'add-expenditure': 'Uitgaven toevoegen',
    'policy-number-label': 'Polisnummer',
    'description-label': 'Omschrijving',
    'amount-label': 'Bedrag',
    'actions-label': 'Acties',
    'condition-label': 'Aandoening',
    delete: 'Verwijderen',
    date: 'Datum',
    'required-field': 'Verplicht veld',
    'invalid-entry': 'Ongeldige invoer',
    'expenses-for-public-transportation': 'Uitgaven voor openbaar vervoer',
    'premium-for-disability-insurance': 'Premie voor arbeidsongeschiktheidverzekering',
    'total-deduction-for-premium-for-disability-insurance': 'Totale aftrek voor arbeidsongeschiktheidsverzekeringen',
    'total-deduction-for-premium-for-general-survivors-law': 'Totale aftrek voor algemene nabestaanden wet',
    'premium-for-general-survivors-law': 'Premies voor algemene nabestaanden wet',
    'premium-for-annuity-of-child': 'Premie voor lijfrente kind',
    /** expenses for public transportation translation */
    'public-transportation-expenses': 'Uitgaven voor openbaar vervoer',
    'distance-single-trip': 'Afstand enkele reis',
    'days-a-week': 'Aantal dagen per week',
    'start-date': 'Startdatum',
    'end-date': 'Einddatum',
    'compensation-label': 'Vergoeding',
    'total-transportation-deductions': 'Totale aftrek voor openbaar vervoer',
    /** premium anniuty translation */
    'premium-for-annuity': 'Premie voor lijfrente',
    'premiums-paid': 'Betaalde premies',
    'policy-number': 'Polisnummer',
    'annual-margin-and-reserve-margin': 'Jaarruimte en reserveringsruimte',
    'edit-annual-reserve-margins': 'Wijzigen jaarruimte en reserveringsruimte',
    'year-label': 'Jaar',
    'profit-from-business': 'Inkomsten uit onderneming',
    'allocation-to-for': 'Dotatie aan FOR',
    'release-of-for': 'Vrijval van FOR',
    'income-from-employment': 'Inkomsten uit arbeid',
    'income-from-other-activities': 'Inkomsten uit overige werkzaamheden',
    'income-from-benefits': 'Inkomsten uit uitkeringen',
    'factor-a-label': 'Factor A',
    'deducted-premiums': 'Afgetrokken premie',
    'total-deduction-for-annuity': 'Totale aftrek voor lijfrentepremies',
    'total-deduction-for-gifts': 'Totale aftrek voor giften',
    'total-deduction-for-premium-for-annuity-of-child': 'Totale aftrek voor lijfrente kind',
    /** alimony translation */
    alimony: 'Alimentatie',
    'edit-alimony': 'Wijzigen alimentatie',
    'alimony-paid': 'Betaalde alimentatie',
    'alimony-paid-to': 'Alimentatie betaald aan',
    'lump-sum': 'Afkoopsom',
    'periodic-payments': 'Periodieke betalingen',
    'settlement-pension-rights': 'Verrekening pensioenrechten',
    welfare: 'Bijstand',
    'other-alimony': 'Overige alimentatie',
    'total-deduction-for-alimony': 'Totale aftrek voor alimentatie',
    initials: 'Initialen',
    'first-name': 'Voornaam',
    'middle-name': 'Tussenvoegsel',
    'last-name': 'Achternaam',
    street: 'Straat',
    'house-number': 'Huisnummer',
    'addition-to-home-number': 'Toevoeging',
    'zip-code': 'Postcode',
    city: 'Woonplaats',
    country: 'Land',
    bsn: 'BSN',
    'date-of-birth': 'Geboortedatum',
    select: 'Selecteren',
    /** Gifts to charity trnslation */
    'gifts-to-charity': 'Giften',
    'paid-gifts': 'Betaalde giften',
    'general-gifts-to-charity': 'Normale giften',
    'cultural-anbi': 'Culturele ANBI',
    'threshold-label': 'Drempel',
    'periodic-gifts-to-charity': 'Periodieke giften',
    'transaction-number': 'Transactienummer',
    'rsin-label': 'RSIN',
    'total-deductions-for-gift-to-charity': 'Totale aftrek voor giften',
    cancel: 'Annuleren',
    save: 'Opslaan',
    yes: 'Ja',
    no: 'Nee',
    /** Expenses for healthcare */
    'expenses-for-healthcare': 'Zorgkosten',
    treatment: 'Behandelingen',
    'prescribed-medication': 'Voorgeschreven medicijnen',
    aids: 'Hulpmiddelen',
    'additional-family-support': 'Extra gezinshulp',
    'prescribed-diet': 'Voorgeschreven dieet',
    'travel-expenses-for-healthcare': 'Reiskosten',
    'travel-expenses-for-hospital-visit-of-family-member': 'Reiskosten ziekenbezoek',
    'extra-expenses-for-clothes-and-linen': 'Extra uitgaven kleding en beddengoed',
    'apply-standard-amount': 'Heeft recht op standaard bedrag',
    'raise-of-standard-amount': 'Heeft recht op verhoogd bedrag',
    'extra-expenses-incompatibilities': 'Extra kosten onverenigbaarheden',
    'total-deduction-for-healthcare-expenses': 'Totale aftrek voor zorgkosten',
    'therapy-treatment': 'Behandeling',
    'travel-expenses-for-healthcare-pop-up-label': 'Reiskosten voor gezondheidszorg',
    'expenses-for-travel-by-ambulance': 'Uitgaven voor vervoer per ambulance',
    'expenses-per-km-in-cents': 'Kosten per km in centen',
    'distance-round-trip': 'Afstand retour reis',
    'number-of-visits': 'Aantal bezoeken',
    'actual-costs-public-transprotation': 'Werkelijke kosten openbaar vervoer',
    'extra-travel-expenses-for-healthcare': 'Extra reiskosten voor gezondheidszorg',
    'total-distance-for-healthcare-in-km': 'Totale afstand gezondheidszorg in km',
    /** educational expenses */
    'educational-expenses': 'Studiekosten',
    'expenses-for-education-without-study-grant': 'Studiekosten studie zonder beurs',
    'expenses-for-education-with-study-grant': 'Kosten voor studie met studiebeurs',
    'study-grant-repaid': 'Terugbetaalde studiebeurs',
    'start-of-study-period': 'Begin studieperiode',
    'end-of-study-period': 'Eind studieperiode',
    'total-deduction-for-educational-expenses': 'Totale aftrek voor studiekosten',
    'educational-year': 'Schooljaar',
    'amount-paid-back': 'Bedrag terugbetaald',
    mbo: 'MBO',
    hbOWO: 'HBO WO',
    /** Weekend expenses for children with disabilities */
    'weekend-expenses-for-children-with-disabilities': 'Weekenduitgaven gehandicapt kind',
    'days-of-care': 'Aantal dagen verzorging',
    'days-traveled': 'Aantal dagen gereisd',
    compensation: 'Vergoeding',
    'total-deduction-for-children-with-disabilities': 'Totale aftrek weekenduitgaven gehandicapt kind',
    /** waived venture capital */
    'waived-venture-capital': 'Verliezen op durfkapitaal',
    'already-waived': 'Reeds kwijtgescholden',
    'amount-waived-this-year': 'Kwijtgescholden in dit jaar',
    'total-deduction-for-waived-venture-capital': 'Totale aftrek verliezen op durfkapitaal',
    'study-grant': 'Studiebeurs',
    reimbursement: 'Vergoeding (B)',
    'total-expenses': 'Totale kosten (A)',
    'total-after-reimbursement': 'Totaal na vergoedingen (A-B)'
  },
});
