import { localize } from '@visionplanner/vp-ui-fiscal-library';

const { extend, translateWithPrefix } = localize();
export const incomeFromBusinessTranslate = translateWithPrefix('tax-forecast-income-from-business');
extend('nl', {
  'tax-forecast-income-from-business': {
    select: 'Selecteren',
    'taxable-subjects': 'Belastingplichtigen',
    'tax-forecast': 'Belastingprognose',
    description: 'Omschrijving',
    commercial: 'Commercieel',
    fiscal: 'Fiscaal',
    comment: 'Commentaar',
    delete: 'Verwijderen',
    date: 'Datum',
    income: 'Inkomsten',
    cost: 'Kosten',
    correction: 'Correctie',
    corrections: 'Correcties',
    'business-activities': 'Bedrijfsactiviteit',
    'legal-form': 'Ondernemingsvorm',
    country: 'Land',
    'start-date-of-business': 'Begin onderneming',
    'end-date-of-business': 'Einde onderneming',
    'fiscal-year-start-date': 'Begin boekjaar',
    'fiscal-year-end-date': 'Einde boekjaar',
    RSIN: 'RSIN',
    add: 'Toevoegen',
    'add-new-administration': 'Nieuwe onderneming toevoegen',
    cancel: 'Annuleren',
    save: 'Opslaan',
    business: 'Onderneming',
    'business-details': 'Ondernemingsgegevens',
    'visionplanner-administration': 'Visionplanner-administratie',
    'profit-and-loss': 'Winst- en verliesrekening',
    name: 'Naam',
    'business-name': 'Ondernemingsnaam',
    administration: 'Administratie',
    'start-fiscal-year': 'Begin boekjaar',
    'end-fiscal-year': 'Einde boekjaar',
    'income-from-business': 'Inkomsten uit onderneming',
    'administration-error': 'Administratie is al gekoppeld aan dit dossier',
    revenue: 'Omzet',
    'total-revenue': 'Omzet-totaal',
    'financial-and-extraordinary-benefits': 'Financiële en buitengewone baten',
    'total-financial-benefits': 'Financiële baten-totaal',
    'financial-benefits': 'Financiële baten',
    'total-extraordinary-benefits': 'Buitengewone baten-totaal',
    'extraordinary-benefits': 'Buitengewone baten',
    'business-costs': 'Ondernemingskosten',
    'financial-and-extraordinary-costs': 'Financiële en buitengewone lasten',
    'total-income-a': 'Totaal inkomsten (A)',
    'purchase-costs': 'Inkoopkosten',
    'personal-costs': 'Personeelskosten',
    'depreciation-costs': 'Afschrijvingen',
    'car-and-transportation-costs': 'Autokosten',
    'housing-costs': 'Huisvestingskosten',
    'selling-csots': 'Verkoopkosten',
    'other-costs': 'Overige kosten',
    'total-business-costs-b1': 'Totaal ondernemingskosten (B1)',
    'total-financial-costs': 'Financiële lasten-totaal',
    'financial-costs': 'Financiële lasten',
    'total-extaordinary-costs': 'Buitengewone lasten-totaal',
    'extaordinary-costs': 'Buitengewone lasten',
    'total-financial-and-extraordinary-costs-b2': 'Totaal financiële en buitengewone lasten (B2)',
    'total-cost-b': 'Totaal kosten (B = B1 + B2)',
    'total-exempted-profit': 'Totaal vrijgestelde winstbestandsdelen',
    'total-non-or-partly-deductable-costs': 'Totaal niet of beperkt aftrekbare kosten',
    'total-corrections-d': 'Totaal fiscale correcties (D)',
    'result-c': 'Resultaat (C = A - B)',
    'final-result-e': 'Fiscaal resultaat (E = C - D)',
    edit: 'Wijzigen',
    'balance-sheet': 'Balans',
    assets: 'Bezittingen',
    'intangible-fixed-assets': 'Immateriële vaste activa',
    'tangible-fixed-assets': 'Materiële vaste activa',
    'financial-fixed-assets': 'Financiele vaste activa',
    'stock-or-inventory': 'Voorraad',
    receivables: 'Vorderingen',
    securities: 'Effecten',
    'liquid-assets': 'Liquide middelen',
    'total-assets': 'Totaal bezittingen',
    'opening-balance-warning': ' Bij de openingsbalans moeten activa en passiva in evenwicht zijn.',
    'closing-balance-warning': ' Bij de slotbalans moeten activa en passiva in evenwicht zijn.',
    note: 'Notitie',
    liabilities: 'Schulden',
    'total-liabilities': 'Totaal schulden',
    'equity-capital': 'Eigen vermogen',
    provisions: 'Voorzieningen',
    'long-term-liabilities': 'Langlopende schulden',
    'short-term-liabilities': 'Kortlopende schulden',
    'purchase-value': 'Aankoopwaarde',
    'residual-value': 'Restwaarde',
    'base-value': 'Bodemwaarde',
    'nominal-value': 'Nominale waarde',
    'vat-this-year': 'BTW dit jaar',
    'vat-last-year': 'BTW vorig jaar',
    'vat-other-years': 'BTW andere jaren',
    'edit-intangible-fixed-assets': 'Wijzigen immateriële vaste activa',
    'edit-tangible-fixed-assets': 'Wijzigen materiële vaste activa',
    'edit-financial-fixed-assets': 'Wijzigen financiele vaste activa',
    'edit-stock-inventory': 'Wijzigen voorraad',
    'edit-receivables': 'Wijzigen vorderingen',
    'edit-liquid-assets': 'Wijzigen liquide middelen',
    'edit-securities': 'Wijzigen effecten',
    'edit-equity-capital': 'Wijzigen eigen vermogen',
    'edit-provisions': 'Wijzigen voorzieningen',
    'edit-long-term-liabilities': 'Wijzigen langlopende schulden',
    'edit-short-term-liabilities': 'Wijzigen kortlopende schulden',
    'other-items': 'Fiscaal resultaat',
    'deposits-withdrawals': 'Stortingen en Onttrekkingen',
    deposits: 'Stortingen',
    withdrawals: 'Onttrekkingen',
    'allocation-result': 'Aandeel in resultaat',
    'allocation-result-to-partner': 'Toewijzing van aandeel in resultaat aan vennoot/firmant',
    'total-allocation-result-to-partner': 'Totaal aandeel in resultaat van vennoot/firmant',
    'share-in-equity-capital': 'Aandeel in eigen vermogen',
    'share-in-equity-capital-of-partner': 'Aandeel in eigen vermogen van vennoot/firmant',
    'total-share-in-equity-capital': 'Totaal aandeel in eigen vermogen van vennoot/firmant',
    'result-profit-loss': 'Resultaat volgens winst- en verliesrekening',
    'result-balance-sheet': 'Resultaat volgens vermogensvergelijking',
    'difference-label': 'Verschil',
    'fiscal-result': 'Fiscaal resultaat',
    'fiscal-result-calculation': 'Berekening fiscaal resultaat',
    'business-result': 'Ondernemingsresultaat',
    'non-partly-deductable-costs': 'Niet of beperkt aftrekbare kosten',
    'allocation-release-equalisation-reserve': 'Dotatie of onttrekking egalisatiereserve (ER)',
    'allocation-release-reinvestment-reserve': 'Dotatie of onttrekking herinvesteringsreserve (HIR)',
    'tax-exempt-components': 'Vrijgestelde winstbestandsdelen',
    'cessation-profit': 'Stakingswinst',
    'investment-deduction': 'Investeringsaftrek',
    'divestment-addition': 'Desinvesteringsbijtelling',
    'allocation-release-fiscal-pension-reserve': 'Dotatie of onttrekking fiscaal oudedagsreserve (FOR)',
    'final-result': 'Fiscaal resultaat',
    opening: 'Begin',
    allocation: 'Dotatie',
    release: 'Vrijval',
    closing: 'Eind',
    'commissioning-date': 'Ingebruikname',
    base: 'Grondslag',
    'percentage-kia': 'Percentage KIA',
    share: 'Aandeel',
    'claim-kia': 'Claim KIA',
    'amount-kia': 'Bedrag KIA',
    'amount-paid': 'Bedrag betaald',
    'claim-eia': 'Claim EIA',
    'amount-eia': 'Bedrag EIA',
    'eia-reference-number': 'EIA meldingsnummer',
    'claim-mia': 'Claim MIA',
    'amount-mia': 'Bedrag MIA',
    'mia-reference-number': 'MIA meldingsnummer',
    'mia-letter': 'MIA letter',
    amount: 'Bedrag',
    'remainder-investment-deduction': 'Restantinvesteringsaftrek',
    entrepreneur: 'Ondernemer',
    'entrepreneur-allowance': 'Ondernemersaftrek',
    'entrepreneurial-deductions': 'Ondernemersaftrek',
    'remainder-self-employed-deduction': 'Restant zelfstandigenaftrek',
    'fiscal-pension-reserve': 'Fiscale oudedagsreserve',
    'add-entrepreneur': 'Ondernemer toevoegen',
    'entitled-to-self-employed-deduction-compiles-with-hour-criterion': 'Krijgt zelfstandigenaftrek, voldoet aan het urencriterium',
    'entitled-to-start-up-deduction': 'Krijgt startersaftrek',
    'entitled-to-start-up-deduction-with-disability': 'Krijgt startersaftrek bij arbeidsongeschiktheid',
    'number-of-times-start-up-deduction-applied': 'Aantal keer startersaftrek geclaimd',
    'entitled-to-research-and-development-deduction': 'Krijgt speur- en ontwikkelingsaftrek',
    'entitled-to-increase-of-research-and-development-deduction': 'Krijgt verhoging van speur- en ontwikkelingsaftrek',
    'research-and-development-statement-number': 'Verklaringsnummer speur- en ontwikkelingsaftrek',
    'number-of-hours-worked-by-assisting-parnter': 'Meewerkuren fiscaal partner',
    'entitled-to-cessation-deduction': 'Krijgt stakingsaftrek',
    'previously-used-cessation-deduction': 'Reeds gebruikte stakingsaftrek',
    'allocate-to-fiscal-pension-reserve': 'Doteren aan fiscale oudedagsreserve',
    'release-of-fiscal-pension-resrve-because-of-paid-annuity-premium': 'Vrijval van fiscale oudedagsreserve vanwege betaalde lijfrente',
    'allocation-details': 'Verdeling',
    'required-field': 'Verplicht veld',
    'invalid-entry': 'Ongeldige invoer',
    'entrepreneur-heading': 'Winst uit onderneming',
    'value-added-tax': 'Omzetbelasting',
    buildings: 'Gebouwen',
    actions: 'Acties',
    'rounding-difference': 'Afrondingsverschil',
    'tax-amount': 'Resultaat aangifte',
    // confirmation dialog translations
    'confirmation-no': 'Annuleren',
    'confirmation-yes': 'Verwijderen',
    'confirmation-question': 'Weet je zeker dat je deze administratie wilt verwijderen?',
    'confirmation-question-to-update-data-source': 'Alle correcties worden verwijderd en commerciele waarden worden overschreven. Wil je doorgaan?',
    'confirmation-title': 'Bevestiging',
    'Partnership-label': 'Vennoot/firmant nummer in administratie',
  },
});
