import { localize } from '@visionplanner/vp-ui-fiscal-library';

const { extend, translateWithPrefix } = localize();
export const incomeTranslate = translateWithPrefix('tax-forecast-income-form');
extend('nl', {
  'tax-forecast-income-form': {
    cost: 'Kosten',
    select: 'Selecteren',
    'required-field': 'Verplicht veld',
    'invalid-entry': 'Ongeldige invoer',
    comment: 'Commentaar',
    delete: 'Verwijderen',
    'taxable-subjects': 'Belastingplichtigen',
    'tax-forecast': 'Belastingprognose',
    income: 'Inkomsten',
    description: 'Omschrijving',
    'employment-discount': 'Arbeidskorting',
    'withheld-wages-tax': 'Loonheffing',
    amount: 'Bedrag',
    actions: 'Acties',
    'save-text': 'Opslaan',
    'add-income': 'Inkomsten toevoegen',
    'country-code': 'Land',
    'income-from-employment': 'Tegenwoordige dienstbetrekking',
    'subjected-to-dutch-tax': 'Belast in nederland',
    'withhold-wages-tax-abroad': 'Bronbelasting',
    'method-for-avoiding-double-taxation': 'Verrekenmethode toepassen',
    'payment-zvw-yet-to-be-done': 'Afdracht ZVW berekenen',
    'general-compensation-applicable': 'Algemene compensatieregeling',
    'additional-compensation-applicable': 'Bijzondere compensatieregeling',
    'change-of-employer': 'Verandering van werkgever',
    'in-belgium-or-germany-withheld-tax': 'Ingehouden belasting',
    'compensation-scheme-in-germany': 'Compensatieregeling',
    'current-employment': 'Tegenwoordige dienstbetrekking',
    'part-of-national-insurance-contribution': 'Premieloon volksverzekeringen',
    'opening-value': 'Waardeopening',
    'closing-value': 'Waardeslot',
    'negative-expenses-income-provisions': 'Terugontvangen premies voor inkomensvoorzieningen',
    'refunded-premium-occupational-disability-insurance': 'Terugontvangen premies voor arbeidsongeschiktheidsverzekering',
    'refunded-premium-annuity': 'Terugontvangen premies voor lijfrente',
    'negative-personal-deduction': 'Negatieve persoonsgebonden aftrek',
    'refunded-alimony': 'Terugontvangen alimentatie',
    'refunded-healthcare-costs': 'Terugontvangen zorgkosten',
    'refunded-study-costs': 'Terugontvangen studiekosten',
    'refunded-maintenance-costs-monumental-object': 'Terugontvangen onderhoudskosten monumenten panden',
    'refunded-gift-to-charities': 'Terugontvangen giften',
    'refunded-waived-venture-capital': 'Terugontvangen kwijtgescholden durfkapitaal',
    'income-out-of-interest-before': 'Inkomsten van lopende rente termijnen',
    'other-income-before': 'Inkomsten van uitgestelde termijnen',
    'income-out-of-capital-insurance': 'Uitkeringen van kapitaalverzekering (niet eigen woning)',
    'current-employment-income': 'Inkomsten uit tegenwoordige arbeid',
    'previous-employment-income': 'Inkomsten uit vroegere arbeid',
    'taxable-income-abroad': 'Inkomsten uit het buitenland',
    'exempted-income-from-international-organization': 'Inkomsten van internationale organisaties',
    'gain-or-cost-from-other-activities': 'Resultaat uit overige werkzaamheden',
    'gain-from-other-activities': 'Inkomsten uit overige werkzaamheden',
    'cost-from-other-activities': 'Kosten van overige werkzaamheden',
    'gain-or-cost-from-making-assets-available-to-own-company': 'Resultaat uit terbeschikkingstellingsregeling',
    'assets-and-liabilities': 'Bezittingen en schulden',
    alimony: 'Alimentatie',
    'income-and-cost-from-benefits': 'Inkomsten uit andere uitkeringen',
    'refund-expenses': 'Terugontvangen bedragen',

    'other-income': 'Belastbare inkomsten op basis van overgangsrecht',
    'income-based-on-transitional-law': 'Inkomsten op basis van overgangsrecht',

    'income-from-benefits': 'Inkomsten uit andere uitkeringen',
    'cost-from-benefits': 'Kosten van andere uitkeringen',
    'gain-from-making-assets-available-to-own-company': 'Inkomsten uit Terbeschikkingstellingsregeling',
    'cost-from-making-assets-available-to-own-company': 'Kosten van Terbeschikkingstellingsregeling',
    'other-assets': 'Overige bezittingen',
    'tangible-property': 'Onroerende zaken',
    'liabilities-with-regards-to-other-activities': 'Schulden',
    'alimony-received': 'Inkomsten uit alimentatie',
    'cost-with-regards-to-alimony': 'Kosten van alimentatie',
    'other-income-Interest-Out-of-Capital-Insurance': 'Belastbare inkomsten op basis van overgangsrecht',
    yes: 'Ja',
    no: 'Nee',
    // confirmation dialog translations
    'confirmation-no': 'Annuleren',
    'confirmation-yes': 'Verwijderen',
    'confirmation-question': 'Weet je zeker dat je deze administratie wilt verwijderen?',
    'confirmation-title': 'Bevestiging',
    'Partnership-label': 'Vennoot/firmant nummer in administratie',
    cancel: 'Annuleren',
    save: 'Opslaan',
  },
});
