import { localize } from '@visionplanner/vp-ui-fiscal-library';

const { extend, translateWithPrefix } = localize();
export const assetsTranslate = translateWithPrefix('tax-forecast-assets-form');
extend('nl', {
  'tax-forecast-assets-form': {
    assets: 'Bezittingen',
    'substantial-interest': 'Aanmerkelijk belang',
    'own-home': 'Eigen woning',
    'description-label': 'Omschrijving',
    'amount-label': 'Bedrag',
    'belongs-to': 'Eigendom van',
    'monumental-property': 'Monumentaal pand',
    ownership: 'Eigendom',
    'woz-value': 'WOZ-waarde',
    'fixed-rate': 'Vaste rente',
    'calculated-value': 'Berekende waarde',
    actions: 'Acties',
    street: 'Straat',
    'house-number': 'Huisnummer',
    addition: 'Toevoeging',
    'zip-code': 'Postcode',
    city: 'Woonplaats',
    country: 'Land',
    woz: 'WOZ',
    'woz-reference-number': 'WOZ-nummer',
    'percentage-of-ownership': 'Percentage eigendom',
    'start-date': 'Startdatum',
    'end-date': 'Einddatum',
    'vacancy-situation': 'Bijzondere situatie',
    'purchase-date': 'Aankoopdatum',
    'purchase-price': 'Aankoopprijs',
    'purchase-costs': 'Aankoopprijs en kosten',
    edit: 'Wijzigen',
    'date-of-sale': 'Verkoopdatum',
    'loan-for-sold-home': 'Lening voor verkochte woning',
    'selling-price': 'Verkoopprijs',
    'selling-costs': 'Verkoopprijs en kosten',
    'paid-ground-rent': 'Betaalde erfpachtcanon',
    'monumental-reference-number': 'Monumentnummer',
    'expenses-paid': 'Betaalde kosten',
    'received-subsidy': 'Ontvangen subsidie',
    'rental-income': 'Huurinkomsten',
    'costs-of-rental': 'Huurkosten',
    'taxable-part-of-capital-insurance': 'Belastbaar deel kapitaal verzekering',
    cancel: 'Annuleren',
    save: 'Opslaan',
    'required-field': 'Verplicht veld',
    'street-validation-error': 'Straat mag maximaal 500 tekens bevatten',
    'house-no-validation-error': 'Huisnummer mag maximaal 500 tekens bevatten',
    'invalid-entry': 'Ongeldige invoer',
    date: 'Datum',
    'business-name': 'Naam',
    administration: 'Administratie',
    'no-of-shares': 'Aantal aandelen',
    'acquisition-price': 'Verkrijgingsprijs',
    'regular-benefit': 'Regulier voordeel',
    'deductable-costs': 'Aftrekbare kosten',
    'withheld-dividend-tax': 'Ingehouden dividendbelasting',
    'transfer-price': 'Verkoopprijs',
    'deductable-acquisition-price': 'Aftrekbare verkrijgingsprijs',
    'income-from-substantial-interest-abroad': 'Inkomsten uit aanmerkelijk belang in het buitenland',
    'withheld-source-tax': 'Ingehouden bronbelasting',
    'other-properties': 'Andere onroerende zaken',
    no: 'Nee',
    rented: 'Verhuurd',
    leased: 'Verpacht',
    'rent-or-lease': 'Verhuurd of verpacht',
    'lease-agreement-for-more-then-12-years': 'Pachtovereenkomst meer dan 12 jaar',
    'year-lease': 'Jaarpacht',
    'used-to-mark-unusual-business-conditions-for-lease': 'Onzakelijke pacht?',
    'tenant-protection': 'Huurbescherming',
    'year-rent': 'Jaarhuur',
    'used-to-mark-unusual-business-conditions-for-rent': 'Onzakelijke huur?',
    'used-to-declare-if-the-property-is-part-of-bigger-building': 'Zelfstandig deel groter gebouw?',
    'percentage-of-rental': 'Percentage verhuurd',
    'bank-account': 'Bankrekeningen',
    'bank-account-no': 'Rekeningnummer',
    value: 'Waarde',
    'investment-accounts': 'Beleggingsrekeningen',
    'environmental-investments': 'Groene beleggingen',
    dividend: 'Dividend',
    'dividend-rabo-private-account': 'Dividend rabo private account',
    'net-worth-of-periodical-benefits': 'Actuele waarde periodieke uitkeringen',
    'outstanding-loan-or-cash': 'Vorderingen en of contant geld',
    'other-assets': 'Overige bezittingen',
    'non-exempt-capital-insurance': 'Niet vrijgestelde kapitaalverzekeringen',
    select: 'Selecteren',
  },
});
