import { localize } from '@visionplanner/vp-ui-fiscal-library';

const { extend, translateWithPrefix } = localize();
export const personalDetailsTranslate = translateWithPrefix('tax-forecast-personal-form');
extend('nl', {
  'tax-forecast-personal-form': {
    'tax-forecast': 'Belastingprognose',
    'taxable-subject': 'Belastingplichtige',
    'personal-information': 'Persoonlijke gegevens',
    'general-information': 'Algemene informatie',
    'date-of-death': 'Overlijdensdatum',
    date: 'Datum',
    'full-name': 'Naam',
    'first-name': 'Voornaam',
    'representative-details': 'Vertegenwoordiger',
    initials: 'Voorletters',
    'middle-name': 'Tussenvoegsel',
    'last-name': 'Achternaam',
    street: 'Straat',
    'house-number': 'Huisnummer',
    addition: 'Toevoeging',
    zipcode: 'Postcode',
    city: 'Woonplaats',
    country: 'Land',
    bsn: 'BSN',
    select: 'Selecteren',
    'date-of-birth': 'Geboortedatum',
    'age-on': 'Leeftijd op',
    'tax-form': 'Biljetsoort',
    'marital-status-in': 'Burgerlijke staat in',
    'situation-when-living-together': 'Samenwoonsituatie',
    'fiscaal-partner': 'Fiscaal partner',
    'married-or-registered-partnership-for-whole-year': 'Gehuwd/geregistreerd partnerschap hele jaar',
    'living-together-for-whole-year': 'Samenwonend hele jaar',
    'single-for-whole-year': 'Alleenstaand hele jaar',
    'situation-changed-during-year': 'Situatie gewijzigd tijdens het jaar',
    'notarial-cohabitation-contract': 'Notarieel samenlevings contract',
    'a-child-together': 'Samen een kind',
    'recognized-child-of-partner': 'Kind ander erkend',
    'own-house-together': 'Samen eigenaar woning',
    'partners-in-pension-arrangement': 'Partner in pensioenregeling',
    'minor-at-same-address': 'Minderjarig kind op woonadres',
    'fiscal-partner-last-year': 'Vorig jaar fiscaal partner',
    none: 'Geen',
    'situation-changed': 'Situatie gewijzigd',
    'date-of-marriage-or-register-partnership': 'Huwelijksdatum / datum geregistreed partnerschap',
    'date-of-divorce': 'Scheidingsdatum',
    'start-of-period-registered-on-same-address': 'Begindatum samenwonen',
    'end-of-period-registered-on-same-address': 'Einddatum samenwonen',
    'meets-conditions-for-fiscal-partnership?': 'Voldaan aan voorwaarden voor fiscaal partnerschap?',
    'conclusion-for-fiscal-partnership': 'Conclusie fiscaal partnerschap',
    'apply-fiscal-partnership-for-the-whole-year?': 'Kiest voor fiscaal partnerschap voor het hele jaar?',
    children: 'Kinderen',
    add: 'Toevoegen',
    remove: 'Verwijderen',
    'type-label': 'Type',
    'taxable-subject-label': 'Belastingplichtige',
    year: 'Jaar',
    'co-parenting': 'Co-ouderschap',
    'registration-on-address': 'Ingeschreven op adres van',
    'parent-collects-childcare': 'Welke ouder ontvangt kinderbijslag',
    'living-with-taxable-subject-or-fiscal-partner-at-least-3-days-a-week': 'Ten minste 3 dagen woonachtig bij belastingplichtige / fiscaal partner',
    'support-to-significant-extent': 'Onderhoud het kind in belangrijke mate',
    actions: 'Acties',
    change: 'Verandering',
    comment: 'Commentaar',
    delete: 'Verwijderen',
    save: 'Opslaan',
    'invalid-entry': 'Ongeldige invoer',
    yes: 'Ja',
    no: 'Nee',
    'required-field': 'Verplicht veld',
    'joint-declaration': 'Doet samen aangifte?',
    // confirmation dialog translations
    'confirmation-no': 'Annuleren',
    'confirmation-yes': 'Verwijderen',
    'confirmation-question': 'Alle informatie van de fiscaal partner wordt verwijderd. Wil je doorgaan?',
    'confirmation-title': 'Bevestiging',
    others: 'Overige',
  },
});
